remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Dedé o mais brabo]
description: [Repositório criado no workshop do GitHub na CPBR 14. Graduando Ciência da Computação, na Universidade Estadual do Norte Fluminense-UENF, com conhecimento em algumas linguagens:]
